name:                thrift-cli
version:             0.1.0.0
github:              "mut0u/thrift-cli"
license:             BSD3
author:              "savior"
maintainer:          "michael.savior@gmail.com"
copyright:           "2019 savior"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mut0u/thrift-cli#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- bytestring
- filepath >= 1.4.2.1
- hashable
- language-thrift
- megaparsec >=5.0 && <6.0
- network
# - thrift == 0.12.0 # 这 package 完全没进当前的 stackage snapshot
# - language-thrift == 0.11.0.0 # 这 package 完全没进当前的 stackage snapshot
- optparse-applicative >= 0.14.3.0
- regex-pcre
- text
- thrift
- unordered-containers
- vector
- scientific
- split
- megaparsec # 悍然从 stack.yaml 里 extra-deps 的 megaparsec-5.3.1 跳到不限版本（现最新版本 7.0.5）

library:
  source-dirs: src

executables:
  thrift-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thrift-cli

tests:
  thrift-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thrift-cli
